import pickle
from django.shortcuts import render
from .models import PredictionHistory
from django.http import HttpResponse
from reportlab.pdfgen import canvas

heart_model = pickle.load(open("ml_model/heart_model.pkl","rb"))
diabetes_model = pickle.load(open("ml_model/diabetes_model.pkl","rb"))

def predict(request):

    if request.method == "POST":

        disease = request.POST["disease"]

        if disease == "heart":

            data = [
                float(request.POST["age"]),
                float(request.POST["sex"]),
                float(request.POST["cp"]),
                float(request.POST["trestbps"]),
                float(request.POST["chol"]),
                float(request.POST["fbs"]),
                float(request.POST["restecg"]),
                float(request.POST["thalach"]),
                float(request.POST["exang"]),
                float(request.POST["oldpeak"]),
                float(request.POST["slope"]),
                float(request.POST["ca"]),
                float(request.POST["thal"])
            ]

            prediction = heart_model.predict([data])
            probability = heart_model.predict_proba([data])[0][1] * 100


        elif disease == "diabetes":

            data = [
                float(request.POST["Pregnancies"]),
                float(request.POST["Glucose"]),
                float(request.POST["BloodPressure"]),
                float(request.POST["SkinThickness"]),
                float(request.POST["Insulin"]),
                float(request.POST["BMI"]),
                float(request.POST["DiabetesPedigreeFunction"]),
                float(request.POST["Age"])
            ]

            prediction = diabetes_model.predict([data])

        probability =diabetes_model.predict_proba([data])[0][1] * 100
        
        result = "Disease Detected" if prediction[0]==1 else "No Disease"

        PredictionHistory.objects.create(
            disease=disease,
            result=result,
            probability=probability
        )
        

        return render(request,"result.html",{"result":result,"probability":round(probability,2)})

    return render(request,"form.html")

def download_report(request):

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="medical_report.pdf"'

    p = canvas.Canvas(response)

    p.drawString(100,750,"Medical Prediction Report")

    p.drawString(100,700,"Result : Disease Detected")

    p.drawString(100,670,"Generated by Multi Disease Prediction System")

    p.showPage()
    p.save()

    return response